### ISSUE TITLE
is it possible to include a circle rounding the gauge?

### ISSUE THREAD

**Issue by shubh9415** [recogizer/angular-gauge-chart#12]
I am trying to implement a full circle gauge but can't find any way to do it.  I want the  gauge to be the same but a circle rounding it.

**Comment by mmaltsev** [comment]
@shubh9415 This is not possible in the current version of the library. We will consider developing this functionality in the future.

For now, take a look at [this](https://swimlane.github.io/ngx-charts/#/ngx-charts/gauge) library. Hope you will find it helpful.
