### ISSUE TITLE
On Option change, gauge label not updating

### ISSUE THREAD

**Issue by Ajay493** [recogizer/angular-gauge-chart#13]
When I change options parameters, my needle value is getting changed properly. However, my rangeLabel is not updating.

I have a list of users(say) having balance and total amount which I am showing in gauge representation. When I select a particular user, that users balances should be shown in gauge. Needle change is working, however not the rangeLabel. In console.log my option object is updated but not the Gauge value.

**Comment by mmaltsev** [comment]
Just published an updated version of the library. You can get it via `npm i angular-gauge-chart@0.5.3`.

Closing the issue for now. Let us know if it appears again.
