### ISSUE TITLE
Center the chart

### ISSUE THREAD

**Issue by mknaa** [recogizer/angular-gauge-chart#15]
I cannot get the chart in middle of an  element (e.g. div). I tried with `text-align:center` in many parental elements but the chart is orientated on the left every time. I  there a hint?

**Comment by daveo1001** [comment]
give the svg some css.

```
display: block;
margin: 0 auto;
```

**Comment by mmaltsev** [comment]
@mknaa There are multiple solutions to your problem. @daveo1001 actually gave a nice one. Thanks a lot!
Another way is to style `<rg-gauge-chart>` element with
```css
margin-left: calc(50% - $chartWidth / 2);
```

If you need to center it vertically, I would advise to use
```css
display: flex;
align-items: center;
```
for the chart container.
