### ISSUE TITLE
angular ng build --prod failure

### ISSUE THREAD

**Issue by umahesh98** [recogizer/angular-gauge-chart#16]
ERROR in : Type GaugeChartComponent in C:/Users/Documents/iqm/sprint-14-Dec/app/node_modules/angular-gauge-chart/angular-gauge-chart.d.ts is part of the declarations of 2 modules: MainModule in C:/Users/Documents/iqm/sprint-14-Dec/app/src/app/main/main.module.ts and GaugeChartModule
in C:/Users/Documents/iqm/sprint-14-Dec/app/node_modules/angular-gauge-chart/angular-gauge-chart.d.ts! Please consider moving GaugeChartComponent in C:/Users/Documents/iqm/sprint-14-Dec/app/node_modules/angular-gauge-chart/angular-gauge-chart.d.ts to a higher module that imports MainModule in C:/Users/Documents/iqm/sprint-14-Dec/app/src/app/main/main.module.ts and GaugeChartModule in C:/Users/Documents/iqm/sprint-14-Dec/app/node_modules/angular-gauge-chart/angular-gauge-chart.d.ts. You can also create a new NgModule that exports and includes GaugeChartComponent
in C:/Users/Documents/iqm/sprint-14-Dec/app/node_modules/angular-gauge-chart/angular-gauge-chart.d.ts then import that NgModule in MainModule
in C:/Users/Documents/iqm/sprint-14-Dec/app/src/app/main/main.module.ts and GaugeChartModule in C:/Users/Documents/iqm/sprint-14-Dec/app/node_modules/angular-gauge-chart/angular-gauge-chart.d.ts.

**Comment by shashi97** [comment]
Any luck @umahesh98 ?

**Comment by shashi97** [comment]
import { GaugeChartModule } from 'angular-gauge-chart';
Module instead of GaugeChartComponent.

**Comment by mmaltsev** [comment]
It was a mistake in the README. Just fixed.

@shashi97 Thanks a lot for figuring that out!
