### ISSUE TITLE
Change centralLabel font size

### ISSUE THREAD

**Issue by sgiaretto** [recogizer/angular-gauge-chart#19]
I need to change the centralLabel font size, but seems there isn't a corresponding property.

**Comment by mmaltsev** [comment]
@sgiaretto That's true. There is no corresponding property for such a functionality. Changing the `rangeLabelFontSize` updates `centralLabel` font size proportionally. We will consider developing this feature in the future.

For now, I would suggest a workaround, which is to set `rangeLabel` to `['','']`, use `rangeLabelFontSize` in  order to change `centralLabel` font size and to display your own range labels underneath the chart.
