### ISSUE TITLE
needleValue, arcDelimiters is greater than or greater than equal to is not working

### ISSUE THREAD

**Issue by rpvsen** [recogizer/angular-gauge-chart#20]
Hi
needleValue, arcDelimiters is greater than || greater than equal to rangeLabel max or min value  is not working can you please help me to resolve this issue.

below are the configurations

public canvasWidth = 300;
public needleValue = 2000;
public centralLabel = '1000';
public name = 'Gauge chart';
public bottomLabel = '65';
public options = {
    hasNeedle: false,
    needleColor: 'gray',
    needleUpdateSpeed: 1000,
    arcColors: ['rgb(44, 151, 222)', 'lightgray'],
    arcDelimiters: [2000],
    rangeLabel: ['1', '1000'],
    needleStartValue: 50,
};

**Version**
angular-gauge-chart@0.6.0
@angular/cli: ~7.3.1

**Comment by mmaltsev** [comment]
Hi @rpvsen,

Both `needleValue` and values of `arcDelimiters` have to stay in the range `[0, 100]`. Perceive them as percentage but not as absolute values.

Hope that helps. I'll add these notes to the README for clarification.
