### ISSUE TITLE
Increase stroke

### ISSUE THREAD

**Issue by DokurOmkar** [recogizer/angular-gauge-chart#21]
How can I increase the stroke of the half doughnut like this so that the indicator falls on to the doughnut? 

![image](https://user-images.githubusercontent.com/6395329/60920012-28b72a80-a265-11e9-9030-f93937f2117a.png)

**Comment by DokurOmkar** [comment]
![image](https://user-images.githubusercontent.com/6395329/60920068-4c7a7080-a265-11e9-8263-3b08c5defb9d.png)

**Comment by mmaltsev** [comment]
Hi @DokurOmkar,

Unfortunately, this functionality is not available in our library. You can check out and play with all available properties [here](https://recogizer.github.io/gauge-chart/examples/samples/edit.html).
