### ISSUE TITLE
Responsive width of the chart

### ISSUE THREAD

**Issue by jithinlal** [recogizer/angular-gauge-chart#23]
Hi, 
First of all great plugin.
But can i have the width of the chart to be responsive in nature?

**Comment by mmaltsev** [comment]
Hi @jithinlal,
thanks for your kind words!

Unfortunately the width could be configured only via the input property `canvasWidth`.
The only advise I can give you is to fetch the width of the chart's parent element and assign it to the chart itself.

**Comment by jithinlal** [comment]
Ok,

Hope you fix this in a future release, because without this I don't think it will be useful to many users

**Comment by prasad1791** [comment]
@mmaltsev  i tried your solution but it only changes the width of main div. width and height of svg element remains same which assigned to it on the initialization.
