### ISSUE TITLE
How to add Label on ARC

### ISSUE THREAD

**Issue by sbgoswami** [recogizer/angular-gauge-chart#26]
Hello all,

I want to create a gauge chart with label on the arc as shown in the following picture 

![sample](https://user-images.githubusercontent.com/54059729/63839778-87636f80-c99d-11e9-8641-339c977d5fc1.PNG)

or link following URL (last example)
https://recogizer.github.io/gauge-chart/examples/samples/

but unable to re-create it?

**Comment by mmaltsev** [comment]
Hi @sbgoswami,

The options used to produce the last gauge are the following:
```js
let options = {
    hasNeedle: true,
    needleColor: 'black',
    arcColors: [],
    arcDelimiters: [10, 60, 90],
    arcPadding: 6,
    arcPaddingColor: 'white',
    arcLabels: ['35', '210', '315'],
    arcLabelFontSize: false,
    rangeLabel: ['0', '350'],
    centralLabel: '175',
    rangeLabelFontSize: false,
    labelsFont: 'Consolas',
}
```

**Comment by paddy1205** [comment]
The answer given above is not working in the current version. Is anything else that I need to do ?

**Comment by Santoshah** [comment]
@paddy1205 Its working with me. 
![image](https://user-images.githubusercontent.com/3863771/87303640-200cca80-c531-11ea-938d-0d7811a2bffb.png)
