### ISSUE TITLE
Unexpected token: punc ()) error in version 0.7.1

### ISSUE THREAD

**Issue by maihannijat** [recogizer/angular-gauge-chart#28]
The version `0.7.1` throws error while building with `--prod` flag. Debug the error with the following line:
`ng build --prod --named-chunks --verbose --build-optimizer=false --source-map`

And found the error on:
> Unexpected token: punc ()) [./node_modules/gauge-chart/dist/bundle.js:169,0]

The line was causing the problem because of the trailing comma:
```
.attr(
  'transform',
  'translate(' + (n + 2 * e) + ', ' + (n + e) + ')',
)
```
Removed the trailing comma and tried to build again but the error continues to another line as the file has trailing commas. Finally, downgraded back to `0.6.0` and it works fine. This version contains the uglified code with no trailing commas but the latest version has pretty code but with trailing commas.

```
@NgModule({
  declarations: [XYZ],
  imports: [
    ...
    GaugeChartModule,
  ]
})
```

Just to add, I am using the library in my Angular 8 project - not directly building the library with `--prod` flag.

**Comment by cherurg** [comment]
@maihannijat thank you for pointing this out. Please, try the new version `angular-gauge-char@0.7.2` that I just published.

The problem was with `gauge-chart` dependency that stored compiled JS in a wrong way.

**Comment by maihannijat** [comment]
@cherurg  Thanks for the quick fix.
