### ISSUE TITLE
backward compatibility

### ISSUE THREAD

**Issue by muhmadtabrez** [recogizer/angular-gauge-chart#29]
Hi,

    I found this component very useful for our project but at present we are on angular 5 and have no plans to update.I was just wondering the same github project can be made backward compatible or if you have any archives of the same project done in angular 5 it would be helpful.

**Comment by mmaltsev** [comment]
Hi @muhmadtabrez,

Unfortunately, we never released a version for Angular 5. You can use `angular-gauge-chart@0.4.0` for Angular 4 and `angular-gauge-chart@0.5.0` for Angular 6.

Keep in mind that these versions are outdated and may contain bugs that were fixed later.
